name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Build Application JAR
        working-directory: ./
        run: mvn clean package -e -X

      - name: Docker compose build
        working-directory: ./
        run: docker compose build

      - name: Run Docker Compose
        working-directory: ./
        run: docker compose up -d

      - name: Wait for the Application to Start
        run: sleep 30 # Adjust the time if needed

      - name: Test Application
        run: curl --fail http://localhost:80 || exit 1

      - name: Archive Test Reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports        

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest

      - name: Tear Down Docker Compose
        if: always()
        working-directory: ./
        run: docker compose down
